# Project information
site_name: ROS Note
site_url: https://alnicomag.github.io/ros-note/
site_author: Sanada Tatsuya
site_description: ""
copyright: Copyright &copy; 2021-2022 Sanada Tatsuya

# Repository
repo_name: alnicomag/ros-note
repo_url: https://github.com/alnicomag/ros-note
edit_uri: ""

# Configuration
docs_dir: docs
site_dir: site

use_directory_urls: false

theme:
  name: material
  #custom_dir: overrides
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes
    #- toc.integrate
    #- header.autohide
    - content.code.annotate
  palette:
    scheme: default
    primary: orange
    accent: indigo
  font:
    text: Zen Maru Gothic
    code: Source Code Pro
  #favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          fontFamily: verdana
          fontSize: 12px
          darkMode: false
          background: "#fff"
          primaryColor: "#DEDFEF"
          #secondaryColor: "#000"
          #mainBkg: "#0000"  # affect node bkg
          nodeBorder: "#000"
          clusterBkg: "#fff"
          clusterBorder: "#000"
          #titleColor: "#808080"
          edgeLabelBackground: "#eee"
        logLevel: 5
        securityLevel: loose
        startOnLoad: true
        arrowMarkerAbsolute: false
        flowchart:
          diagramPadding: 8
          nodeSpacing: 50
          rankSpacing: 50
          useMaxWidth: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alnicomag
  analytics:
    provider: google
    property: G-72RDHRKN14

extra_css:
  - stylesheets/extra.css
  - https://use.fontawesome.com/releases/v5.15.0/css/all.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Extensions
markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.keys
  - pymdownx.mark
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: §

# Page tree
nav:
  - Home: index.md
  - Linux:
    - linux_literacy/index.md
    - シェルとは: linux_literacy/shell.md
    - コマンド操作: linux_literacy/command.md
    - パーミッション: linux_literacy//permission.md
  - 環境構築:
    - environment_setup/index.md
    - Ubuntu 仮想マシン: environment_setup/ubuntu.md
    - ROS Melodic: environment_setup/ros_melodic.md
  - ROS の基礎:
    - ros_basic/index.md
    - 全体像: ros_basic/outline.md
    - ROS のコマンド: ros_basic/ros_command.md
  - 雑記:
    - memo/index.md
    - URDF: memo/urdf.md
  - 資料集:
    - reference/index.md
    - 書籍: reference/books.md